### ISSUE TITLE
AttributeError: type object 'Orientation' has no attribute 'Portrait'

### ISSUE THREAD

**Issue by karthi-mss007** [adewes/pdf-printer#2]
Traceback (most recent call last):
  File "printer.py", line 23, in <module>
    pdf = generate_pdf(template_path, template_dir, media_dir, context)
  File "C:\Karthi\pdf-printer-master\qtpdf\generate.py", line 34, in generate_pdf
    layout.setOrientation(getattr(QPageLayout.Orientation, page_orientation))
AttributeError: type object 'Orientation' has no attribute 'Portrait'

**Comment by karthi-mss007** [comment]
solution :
 In generate_pdf.py file, at line 34, change to 
layout.setOrientation(getattr(QPageLayout, page_orientation))

**Comment by adewes** [comment]
Which Python and Qt version do you use? `QPageLayout.Orientation.Portrait = 0` for PyQt5==5.11.3, so the code should work fine.

**Comment by karthi-mss007** [comment]
i'm using PyQt5==5.10.1. now i'm updating my pyqt5 installation to 5.11.3. will come back to you with the results.

**Comment by karthi-mss007** [comment]
hi adewes! it works fine for latest version. 

Note: the one I've given (`QPageLayout.Protrait = 0`) as well works. 

Thanks for the guidance!
